steps:
  # Step 1: Install dependencies in a virtual environment
  - name: 'python:3.11'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - |
        python -m venv /workspace/venv
        source /workspace/venv/bin/activate
        pip install -r requirements.txt
        deactivate

  # Step 2: Run tests using pytest
  - name: 'python:3.11'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - |
        source /workspace/venv/bin/activate
        pytest --junitxml=${SHORT_SHA}_test_log.xml
        deactivate

#  - name: 'gcr.io/cloud-builders/gsutil'
#    args: [ '-m', 'cp', '-r', 'gs://book-recommender-lightfm-model-data/profile/$_MODEL_VERSION', '.' ]
#    id: Download model files
#
#  - name: gcr.io/cloud-builders/docker
#    args:
#      - build
#      - '--no-cache'
#      - '--build-arg'
#      - 'MODEL_FILES=$_MODEL_VERSION'
#      - '-t'
#      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
#      - .
#      - '-f'
#      - Dockerfile
#    id: Build
