steps:
  # Step 1: Install all requirements
  - name: python:3.11
    entrypoint: pip
    args: [ "install", "-r", "requirements.txt", "--user" ]

  # Step 3: Run tests using pytest
  - name: python:3.11
    entrypoint: python
    args: [ "-m", "pytest", "--junitxml=${SHORT_SHA}_test_log.xml" ]