steps:
  # Step 1: Run Tests
  - name: python:3.11-slim
    entrypoint: bash
    args:
      - -c
      - |
        pip install --upgrade pip
        pip install poetry
        poetry install
        poetry run pytest --junitxml=${SHORT_SHA}_test_log.xml